import type { User } from '@/lib/types';

export const users: User[] = [
  {
    id: 'user-001',
    name: 'Super Admin',
    email: 'super@tenantverse.com',
    role: 'Super Admin',
    tenantId: 'acme',
    avatar: 'avatar-1',
    phone: '123-456-7890',
    address: '123 Admin Lane',
    status: 'active',
  },
  {
    id: 'user-002',
    name: 'Alice Admin',
    email: 'alice@acme.com',
    role: 'Admin',
    tenantId: 'acme',
    avatar: 'avatar-2',
    phone: '234-567-8901',
    address: '456 Acme Ave',
    status: 'active',
  },
  {
    id: 'user-003',
    name: 'Bob User',
    email: 'bob@acme.com',
    role: 'User',
    tenantId: 'acme',
    avatar: 'avatar-3',
    phone: '345-678-9012',
    address: '789 Acme St',
    status: 'active',
  },
  {
    id: 'user-004',
    name: 'Tony Stark',
    email: 'tony@stark.com',
    role: 'Admin',
    tenantId: 'stark',
    avatar: 'avatar-4',
    phone: '456-789-0123',
    address: '10880 Malibu Point',
    status: 'active',
  },
  {
    id: 'user-005',
    name: 'Pepper Potts',
    email: 'pepper@stark.com',
    role: 'User',
    tenantId: 'stark',
    avatar: 'avatar-5',
    phone: '567-890-1234',
    address: '10880 Malibu Point',
    status: 'inactive',
  },
  {
    id: 'user-006',
    name: 'Bruce Wayne',
    email: 'bruce@wayne.com',
    role: 'Admin',
    tenantId: 'wayne',
    avatar: 'avatar-6',
    phone: '678-901-2345',
    address: 'Wayne Manor',
    status: 'active',
  },
];
